[package]
name = "all-divisions-with-the-highest-score-of-a-binary-array"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
